name: DCO Check

on:
  pull_request:
    branches: [ main, master ]

jobs:
  dco:
    name: DCO Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: DCO Check
        uses: dcoapp/dco-check-action@v1

